### ISSUE TITLE
docs.rs only shows empty crates

### ISSUE THREAD

**Issue by jonas-schievink** [adamgreig/stm32-rs#3]
For example: https://docs.rs/stm32f4/0.1.0/stm32f4/

The features added in https://github.com/onur/docs.rs/pull/73 can be used to make docs.rs build the crates with all features enabled:

```toml
[package.metadata.docs.rs]
all-features = true
```
