### ISSUE TITLE
How to merge registers fields and modify its content?

### ISSUE THREAD

**Issue by octronics** [adamgreig/stm32-rs#47]
I want to merge the CNT_H and CNT_L 16bit field into one 32bit CNT field. I found the `_merge` but it reduce the name as `CNT_`. How can I remove the trailing underscore?
I found the `_modify` and try to update the description of the field, to reflect its meaning and not was as been merged (the CNT_H description). But this doesn't work. The README says that _modify is done first.
```
"TIM2":
  CNT:
    # Actualy a 32bit register
    _merge:
      - "CNT*"
    _modify:
      "CNT_":
        name: CNT
        description: Counter value
        value: [0, 4294967295]
```
Would you please help me?

**Comment by adamgreig** [comment]
This is a bit tricky. Maybe you could use `_modify` first to name them `CNTH` and `CNTL`, and then use `_merge` to combine them without the trailing underscore?

**Comment by octronics** [comment]
Thanks. Will give it a try.

**Comment by octronics** [comment]
I come to that and it works. Feel free to close the issue.
```
"TIM2":
  CNT:
    _modify:
      CNT_H:
        name: CNTH
        description: Counter value
      CNT_L:
        name: CNTL
    _merge:
      - "CNT*"
    CNT: [0, 4294967295]
```
