### ISSUE TITLE
Failed to build with 1.30.0-nightly

### ISSUE THREAD

**Issue by sprhawk** [adamgreig/stm32-rs#63]
environment:
rustc: 1.30.0-nightly (4591a245c 2018-09-22)
stm32f3 version: 0.2.3
features = ["stm32f302", "rt"]

```
  = note: rust-lld: error:
          ERROR(cortex-m-rt): The interrupt vectors are missing.
          Possible solutions, from most likely to less likely:
          - Link to a svd2rust generated device crate
          - Disable the 'device' feature of cortex-m-rt to build a generic application (a dependency
          may be enabling it)
          - Supply the interrupt handlers yourself. Check the documentation for details.
```

A lib I use svd2rust(0.13.1) to generate from [STM32F302.svd](https://github.com/posborne/cmsis-svd/tree/master/data) can be built

**Comment by adamgreig** [comment]
Could you post your full `cargo.toml` and perhaps a minimal `src/main.rs` that replicates the issue? I've just tried a minimal new project which builds fine. Maybe you don't have a `build.rs` script in your project at all? Here's the very very minimal project that builds fine:

cargo.toml:
```toml
[package]
name = "stm32test"
version = "0.1.0"
authors = ["Adam Greig <adam@adamgreig.com>"]

[dependencies]
cortex-m = "0.5.7"
cortex-m-rt = "0.6.4"
panic-abort = "0.3.0"

[dependencies.stm32f3]
version = "0.2.3"
features = ["stm32f303", "rt"]
```

build.rs:
```rust
use std::env;
use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());
    File::create(out.join("memory.x"))
        .unwrap()
        .write_all(include_bytes!("memory.x"))
        .unwrap();
    println!("cargo:rustc-link-search={}", out.display());
}
```

.cargo/config:
```toml
[target.thumbv7em-none-eabihf]
runner = 'arm-none-eabi-gdb'
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "linker=arm-none-eabi-ld",
  "-Z", "linker-flavor=ld",
  "-Z", "thinlto=no",
]

[build]
target = "thumbv7em-none-eabihf"
```

memory.x:
```
MEMORY
{
    FLASH : ORIGIN = 0x08000000, LENGTH = 1M
    RAM :   ORIGIN = 0x20000000, LENGTH = 128K
}
```

src/main.rs:
```rust
#![no_std]
#![no_main]
extern crate cortex_m;
extern crate cortex_m_rt;
extern crate panic_abort;
use cortex_m_rt::entry;
extern crate stm32f3;
use stm32f3::stm32f303;

#[entry]
fn start() -> ! {
    let p = stm32f303::Peripherals::take().unwrap();
    let gpioa = &p.GPIOA;
    gpioa.odr.modify(|_, w| w.odr0().set_bit());
    loop {
        cortex_m::asm::nop();
    }
}
```
