### ISSUE TITLE
Include does not work on peripherals

### ISSUE THREAD

**Issue by octronics** [adamgreig/stm32-rs#67]
To compose a peripheral from multiple common fields, I try to use the _include. But it does not documents the fields.

I declare the common fields on a separate file:
```
REG:
   FIELD:
      VALUE0: [0, "description"]
      VALUE1: [1, "description"]
```
Then I declare the peripheral on its file:
```
PERIPH:
  _include:
     - ../peripherals/periph/common_field.yaml
```
I had to use `../peripherals/periph/` path otherwise `svdpatch` complain it doesn't find the `stm32-rs/devices/common_field.yaml` file.

The actual problem is that the values are not added to the patched svd file.
Do I need to done something different? If not can you help me to made this functionality working.

Thanks.
