### ISSUE TITLE
Consider cross-referencing SVDs to C header files

### ISSUE THREAD

**Issue by adamgreig** [adamgreig/stm32-rs#72]
modm have a lovely repository of slightly-patched C header files extracted from CubeMX [here](https://github.com/modm-io/cmsis-header-stm32). It's not beyond the realm of imagination that we could automatically compare the C header definitions to the SVDs, and catch incorrectly named, missing, and surplus entries.

**Comment by cs2dsb** [comment]
Have you seen the XML files in STM32CubeMX? [Someone has uploaded a copy here](https://github.com/esden/stm32cube-database)

They seem to specify every possible variant of each peripheral (db/mcu/ip/*.xml) and which of them exist on which chip (db/mcu/*.xml).

The peripheral files seem to have a complete list of enumerated values - I've only spot checked but certainly for the MCU I was using the XML was more complete than the SVD or the header files.

Reverse engineering it and doing something useful with them might be a bit of a task but if nothing else it's easier to copy enumerated values from there than the dodgy formatted pdf reference docs. For example:
```
<RefParameter Comment="PLL Mul" DefaultValue="RCC_PLL_MUL2" Name="PLLMUL" Type="list" Visible="false">
  <PossibleValue Comment="2" Value="RCC_PLL_MUL2"/>
...
```

**Comment by cs2dsb** [comment]
I've had a bash at getting something useful out of the CubeMx db xml files. I focussed on getting the interrupts out because the interrupts for the micro I'm using are a mess and managed to generate a complete list:
```
WWDG:
  _add:
    _interrupts:
      WWDG:
        description: Window watchdog interrupt
        value: 0
EXTI:
  _add:
    _interrupts:
      PVD:
        description: PVD interrupt through EXTI line 16
        value: 1
      EXTI0:
        description: EXTI line0 interrupt
        value: 6
      EXTI1:
        description: EXTI line1 interrupt
        value: 7
      EXTI2:
        description: EXTI line2 interrupt
        value: 8
      EXTI3:
        description: EXTI line3 interrupt
        value: 9
      EXTI4:
        description: EXTI line4 interrupt
        value: 10
      EXTI9_5:
        description: EXTI line[9:5] interrupts
        value: 23
      EXTI15_10:
        description: EXTI line[15:10] interrupts
        value: 40
RTC:
  _add:
    _interrupts:
      TAMP_STAMP:
        description: RTC tamper and timestamp interrupts through EXTI line 21
        value: 2
      RTC_WKUP:
        description: RTC wake-up interrupt through EXTI line 22
        value: 3
      RTC_Alarm:
        description: RTC alarms A and B interrupt through EXTI line 17
        value: 41
FLASH:
  _add:
    _interrupts:
      FLASH:
        description: Flash global interrupt
        value: 4
RCC:
  _add:
    _interrupts:
      RCC:
        description: RCC global interrupt
        value: 5
DMA1:
  _add:
    _interrupts:
      DMA1_Stream0:
        description: DMA1 stream0 global interrupt
        value: 11
      DMA1_Stream1:
        description: DMA1 stream1 global interrupt
        value: 12
      DMA1_Stream2:
        description: DMA1 stream2 global interrupt
        value: 13
      DMA1_Stream3:
        description: DMA1 stream3 global interrupt
        value: 14
      DMA1_Stream4:
        description: DMA1 stream4 global interrupt
        value: 15
      DMA1_Stream5:
        description: DMA1 stream5 global interrupt
        value: 16
      DMA1_Stream6:
        description: DMA1 stream6 global interrupt
        value: 17
      DMA1_Stream7:
        description: DMA1 stream7 global interrupt
        value: 47
ADC1:
  _add:
    _interrupts:
      ADC:
        description: ADC1 global interrupt
        value: 18
TIM1:
  _add:
    _interrupts:
      TIM1_BRK_TIM9:
        description: TIM1 break interrupt and TIM9 global interrupt
        value: 24
      TIM1_UP_TIM10:
        description: TIM1 update interrupt and TIM10 global interrupt
        value: 25
      TIM1_TRG_COM_TIM11:
        description: TIM1 trigger and commutation interrupts and TIM11 global interrupt
        value: 26
      TIM1_CC:
        description: TIM1 capture compare interrupt
        value: 27
TIM9:
  _add:
    _interrupts:
      TIM1_BRK_TIM9:
        description: TIM1 break interrupt and TIM9 global interrupt
        value: 24
TIM10:
  _add:
    _interrupts:
      TIM1_UP_TIM10:
        description: TIM1 update interrupt and TIM10 global interrupt
        value: 25
TIM11:
  _add:
    _interrupts:
      TIM1_TRG_COM_TIM11:
        description: TIM1 trigger and commutation interrupts and TIM11 global interrupt
        value: 26
TIM2:
  _add:
    _interrupts:
      TIM2:
        description: TIM2 global interrupt
        value: 28
TIM3:
  _add:
    _interrupts:
      TIM3:
        description: TIM3 global interrupt
        value: 29
TIM4:
  _add:
    _interrupts:
      TIM4:
        description: TIM4 global interrupt
        value: 30
I2C1:
  _add:
    _interrupts:
      I2C1_EV:
        description: I2C1 event interrupt
        value: 31
      I2C1_ER:
        description: I2C1 error interrupt
        value: 32
I2C2:
  _add:
    _interrupts:
      I2C2_EV:
        description: I2C2 event interrupt
        value: 33
      I2C2_ER:
        description: I2C2 error interrupt
        value: 34
SPI1:
  _add:
    _interrupts:
      SPI1:
        description: SPI1 global interrupt
        value: 35
SPI2:
  _add:
    _interrupts:
      SPI2:
        description: SPI2 global interrupt
        value: 36
USART1:
  _add:
    _interrupts:
      USART1:
        description: USART1 global interrupt
        value: 37
USART2:
  _add:
    _interrupts:
      USART2:
        description: USART2 global interrupt
        value: 38
OTG_FS_DEVICE:
  _add:
    _interrupts:
      OTG_FS_WKUP:
        description: USB On The Go FS wake-up interrupt through EXTI line 18
        value: 42
      OTG_FS:
        description: USB On The Go FS global interrupt
        value: 67
SDIO:
  _add:
    _interrupts:
      SDIO:
        description: SDIO global interrupt
        value: 49
TIM5:
  _add:
    _interrupts:
      TIM5:
        description: TIM5 global interrupt
        value: 50
SPI3:
  _add:
    _interrupts:
      SPI3:
        description: SPI3 global interrupt
        value: 51
DMA2:
  _add:
    _interrupts:
      DMA2_Stream0:
        description: DMA2 stream0 global interrupt
        value: 56
      DMA2_Stream1:
        description: DMA2 stream1 global interrupt
        value: 57
      DMA2_Stream2:
        description: DMA2 stream2 global interrupt
        value: 58
      DMA2_Stream3:
        description: DMA2 stream3 global interrupt
        value: 59
      DMA2_Stream4:
        description: DMA2 stream4 global interrupt
        value: 60
      DMA2_Stream5:
        description: DMA2 stream5 global interrupt
        value: 68
      DMA2_Stream6:
        description: DMA2 stream6 global interrupt
        value: 69
      DMA2_Stream7:
        description: DMA2 stream7 global interrupt
        value: 70
USART6:
  _add:
    _interrupts:
      USART6:
        description: USART6 global interrupt
        value: 71
I2C3:
  _add:
    _interrupts:
      I2C3_EV:
        description: I2C3 event interrupt
        value: 72
      I2C3_ER:
        description: I2C3 error interrupt
        value: 73
FPU:
  _add:
    _interrupts:
      FPU:
        description: FPU global interrupt
        value: 81
SPI4:
  _add:
    _interrupts:
      SPI4:
        description: SPI4 global interrupt
        value: 84
SPI5:
  _add:
    _interrupts:
      SPI5:
        description: SPI5 global interrupt
        value: 85
```

I'm currently reading the mcu xml file to get a list of the IP it has and the NVIC IP xml file to get the interrupts. Using the CubeMx executable as reference I managed to extract the logic they use to get the peripheral names from the interrupt list. 
The C header defines for the values are directly constructed from info in the NVIC xml so it's fairly straightforward to extract the values. I've currently got a little bash file that finds all the defines for a given symbol in the headers for all the different devices f0-7 and plops out the values. As it turns out, the f0 often has different interrupt values but all the other devices are the same. In theory the same can be done with peripheral and register addresses - these may be harder as they can be compound defines - I was wondering about generating little c programs that just print the define I'm looking for...
I'm also using the svd parser from svd2rust to cross reference the peripheral names so it'll only generate output if the peripheral names it's found in the NVIC IP xml match peripherals in the svd file.

I thought I'd comment to say that at least in principle there is some useful data to be extracted but also to see if anyone had any ideas where we should go with it? Currently it's a janky command line tool that can be coerced into giving me the above output which can become a yaml file in this repo once #163 is resolved but in theory it could generate an entirely new SVD. Alternatively it could just be used to fact check the SVD files and print out a big list of differences which we could patch until the tool says the SVD is right.
